import pandas as pd
import numpy as np
import os
import re
import glob
from snakemake.utils import min_version
from snakemake.utils import validate

configfile: "config/config.yaml"

sample_metadata = pd.read_excel(config['sample_metadata'], header=0)
sample_files = pd.read_excel(config['sample_files'], header=0)

fastq_basenames = pd.Series(pd.concat([sample_files['Basename_fastq'], sample_files['Basename_fbc_fastq']]), name = 'files')
fastq_basenames = fastq_basenames[fastq_basenames.notna()]

fastq_df = pd.concat({'old_path' : fastq_basenames,
                      'file' : fastq_basenames.apply(lambda x: os.path.basename(x))},
                     axis=1)
                     
fastq_fns = fastq_df['file'].unique().tolist()

# Files
fastq_df = fastq_df.drop_duplicates()

sample_files_nonfbc = sample_files[sample_files['FBC_type'].isna()].copy()
sample_files_fbc = sample_files[sample_files['FBC_type'].notna()].copy()

# Non-FBC
sample_files_nonfbc['Well10X_str'] = sample_files_nonfbc['Well10X'].astype(str)
runs_nonfbc = pd.Series(sample_files_nonfbc['Run_ID'])

# FBC
sample_files_fbc['Well10X_str'] = sample_files_fbc['Well10X'].astype(str)
runs_fbc = pd.Series(sample_files_fbc['Run_ID'].unique())

runs = pd.concat([runs_nonfbc, runs_fbc], axis=0)

levels = ["manual_l1","manual_l2","manual_l3","manual_l4"]
relative_levels = ["manual_l1rNULL", "manual_l2rNULL", "manual_l3rNULL", "manual_l4rNULL", "manual_l2rmanual_l1", "manual_l3rmanual_l1", "manual_l4rmanual_l1", "manual_l3rmanual_l2", "manual_l4rmanual_l2", "manual_l4rmanual_l3"]
tissues=["PBMC","PF"]
lineages = ["T","NKILC","Myeloid","MNP"]

outputdir = config['output_dir']

include: "rules/fbc_preparation.smk"
include: "rules/resources.smk"
include: "rules/cellranger.smk"
include: "rules/velocyto.smk"
include: "rules/preparation.smk"
# include: "rules/q1_pf_characterization.smk"
# include: "rules/q2_crc_vs_hc.smk"
# include: "rules/q3_pm_tx_characterization.smk"
include: "rules/analyses.smk"

wildcard_constraints:
  run='|'.join([re.escape(x) for x in runs]),
  run_nonfbc='|'.join([re.escape(x) for x in runs_nonfbc]),
  run_fbc='|'.join([re.escape(x) for x in runs_fbc]),
  level='|'.join([re.escape(x) for x in levels]),
  tissue='|'.join([re.escape(x) for x in tissues]),
  relative_level='|'.join([re.escape(x) for x in relative_levels]),
  lineage='|'.join([re.escape(x) for x in lineages]),
  
rule all:
  input:
    # Preparation
    "output/merged/velocyto_merged.loom",
    "output/curated/velocyto_curated.loom",
    "output/curated/curated_SeuratObject.Rds",
    "resources/GSE134355/gse134355_adult_immune_reannotated_SeuratObject.Rds",
    "resources/GSE178318/gse178318_macrophages_SeuratObject.Rds",
    "resources/GSE201333/gse201333_reannotated_SeuratObject.Rds",
    # Part 1: PF of healthy individuals
    ## Subsetting and combining cells
    "output/q1_pf_characterization/subsets/hc_pbmc_pf_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/hc_pbmc_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/hc_pf_SeuratObject.Rds",
    expand("output/q1_pf_characterization/subsets/hc_pf_{lineage}_SeuratObject.Rds", lineage = lineages),
    "output/q1_pf_characterization/subsets/hc_pf_macrophages_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/pbmc_pf_liver_colon_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/liver_mnp_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/liver_macrophages_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/colon_mnp_SeuratObject.Rds",
    "output/q1_pf_characterization/subsets/colon_macrophages_SeuratObject.Rds",
    ## Analyses
    "output/q1_pf_characterization/analyses/hc_pf_manual_l2l3_markerproteins_list.Rds",
    "output/q1_pf_characterization/analyses/hc_pf_macrophages_markerproteins_list.Rds",
    "output/q1_pf_characterization/analyses/hc_pf_macrophages_markergenes_list.Rds",
    "output/q1_pf_characterization/analyses/hc_pf_macrophages_marker_fgsea_list.Rds",
    "output/q1_pf_characterization/analyses/hc_pf_macrophages_tamannotation_scores.Rds",
    # Part 2: PF of PM-CRC patients
    ## Subsetting and combining cells
    "output/q2_crc_vs_hc/subsets/hc_crcpmp_pf_allcells_SeuratObject.Rds",
    "output/q2_crc_vs_hc/subsets/hc_crcpmp_pf_SeuratObject.Rds",
    "output/q2_crc_vs_hc/subsets/crcpmp_pf_macrophages_SeuratObject.Rds",
    ## Analyses
    expand("output/q2_crc_vs_hc/analyses/degs_crcvhc_{tissue}_{level}_list.Rds", tissue = ["PBMC", "PF"], level = ["manual_l2","manual_l3","manual_l4"]),
    expand("output/q2_crc_vs_hc/analyses/fgsea_crcvhc_{tissue}_{level}_list.Rds", tissue = ["PBMC", "PF"], level = ["manual_l2","manual_l3","manual_l4"]),
    # Part 3: TX of PM-CRC patients
    ## Subsetting and combining cells
    "output/q3_pm_tx_characterization/subsets/hc_crcpmp_pbmc_pf_tx_paired_monocytes_macrophages_SeuratObject.Rds",
    "output/q3_pm_tx_characterization/subsets/crcpmp_tx_immune_SeuratObject.Rds",
    "output/q3_pm_tx_characterization/subsets/crcpmp_tx_macrophages_SeuratObject.Rds",
    "output/q3_pm_tx_characterization/subsets/crcpmp_tx_monocytes_macrophages_SeuratObject.Rds",
    ## Analyses
    "output/q3_pm_tx_characterization/analyses/crcpmp_pf_tx_paired_macrophages_tamannotation.Rds",
    "output/q3_pm_tx_characterization/subsets/crcpmp_tx_macrophages_trajectory_sce.Rds",
    "output/q3_pm_tx_characterization/analyses/crcpmp_tx_monocytes_macrophages_scvelo_anndata.h5ad",
