#!/usr/bin/env Rscript
# The goal of this script is to select the PBMC-, PF-, and TX-derived cells from the donors that provided all three only.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop(paste0("Script needs 4 arguments. Current input is:", args))
}

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(SeuratDisk))
suppressPackageStartupMessages(library(dplyr))

seurat_rds_path <- args[1]
pbmc_pf_tx_paired_seurat_rds_path <- args[2]

seuratObject <- readRDS(seurat_rds_path)

txdonors <- unique(seuratObject@meta.data$Donor[seuratObject@meta.data$Tissue == "TX"])

pbmc_pf_tx_paired_seuratObject <- seuratObject[,seuratObject@meta.data$Donor %in% txdonors]

# Save data
saveRDS(pbmc_pf_tx_paired_seuratObject, pbmc_pf_tx_paired_seurat_rds_path, compress = "gzip")

sessionInfo()