#!/usr/bin/env Rscript
# This script will generate the following plots from the PBMC and PF tissue samples comparing CRC+ with CRC- for the manual_l3 relative to manual_l2 abundances. 

suppressPackageStartupMessages(library(Seurat))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(ggrastr))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(svglite))

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 3) {
  stop(paste0("Script needs 3 arguments. Current input is:", args))
}

seurat_rds_path <- args[1]
plot_df_csv_path <- args[2]
fig_svg_path <- args[3]

seuratObject <- readRDS(seurat_rds_path)

seuratObject <- seuratObject[, seuratObject@meta.data$Tissue %in% c("PBMC", "PF")]

l3rl2_abundances <- seuratObject@meta.data %>%
  dplyr::group_by(manual_l2, manual_l3, Donor, Group, Tissue) %>% 
  dplyr::summarise(Ncells = n()) %>%
  dplyr::group_by(manual_l2, Donor, Group, Tissue) %>%
  dplyr::mutate(Nsample = sum(Ncells),
                Ncellprop = Ncells/Nsample,
                Entity = paste0(manual_l3, "\n", Tissue))

write.csv(l3rl2_abundances, plot_df_csv_path)

l3rl2_crcpvcrcn_abundances_plot <- ggplot(l3rl2_abundances, aes(x = Group, y = Ncellprop)) +
  geom_boxplot(alpha = 0.5) +
  geom_point(alpha = 0.5) +
  facet_wrap(~Entity, scales = "free_y") +
  labs(title = "Metastatic vs non-metastatic",
       subtitle = "Proportion l3 relative to l2",
       y = "Proportion") +
  theme_bw() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        axis.title.x = element_blank(),
        legend.pos = "bottom",
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

svglite(width = 30, height = 30, file = fig_svg_path, bg = "white")
print(l3rl2_crcpvcrcn_abundances_plot)
dev.off()

sessionInfo()