---
title: "UEG 2022"
author: "Andrew Y.F. Li Yim"
date: '2022-09-23'
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
require(dplyr)
require(Seurat)
require(DESeq2)
require(GetoptLong)
require(ComplexHeatmap)
```

```{r import}
pbmc_pf_tx_seuratObject <- readRDS("/media/hdd1/andrewliyim/maps_crc/output/subsets/pbmc_pf_tx_SeuratObject.Rds")
```

```{r samples of interest}
ueg_samples <- pbmc_pf_tx_seuratObject@meta.data %>%
  dplyr::select(SampleID, Donor, Sex, Tissue, Metastasis, Group) %>%
  unique() %>%
  dplyr::filter(Donor %in% c("pt50", "pt72", "pt79", "pt81", "pt25", "pt37", "pt71", "pt31", "pt74", "pt76", "pt78"),
                !SampleID %in% c("pt78_PBMC", "pt78_PF"))
rownames(ueg_samples) <- ueg_samples$SampleID
```

## Patient metadata

```{r patient metadata}
patient_metadata <- readxl::read_excel(file.path("config", "samples", "patient_metadata.xlsx")) %>%
  #dplyr::filter(grepl("(CRC|HC)", group)) %>%
  dplyr::rename("PatientID" = "patient nr",
                "CastorID" = "castor ID",
                "Age" = "age at surgery",
                "Sex" = "seks",
                "Group" = "group",
                "MMR" = "MMR status primary tumor (MMRp/MMRd)",
                "Omics" = "entity",
                "Tumor_omics" = "Tx entity",
                "Cancer_stage" = "Stage",
                "T_stage" = "T",
                "N_stage" = "N",
                "M_stage" = "M",
                "PM" = "PM status",
                "MAPS_CRC" = "in study 'CRC MAPS'",
                "MAPS_GC" = "in study 'GC MAPS'",
                "PF_ATLAS" = "in study 'atlas'") %>%
  dplyr::mutate(PatientID = paste0("pt", PatientID),
                Group = gsub("(\\+|\\-)", "", Group),
                Group = gsub(" \\(HIPEC\\)", "", Group),
                Group = gsub(" ", "", Group),
                BMI = as.numeric(BMI),
                Sex = stringr::str_to_title(Sex),
                PM = stringr::str_to_title(PM),
                PM = gsub("Na", NA, PM),
                PM = gsub("Pm\\+", "Yes", PM),
                PM = gsub("Pm\\-", "No", PM),
                PM = gsub("Hc", NA, PM),
                MAPS_CRC = stringr::str_to_title(MAPS_CRC),
                MAPS_GC = stringr::str_to_title(MAPS_GC),
                PF_ATLAS = stringr::str_to_title(PF_ATLAS),
                HIPEC = stringr::str_to_title(HIPEC),
                HIPEC = gsub("Hc", NA, HIPEC),
                Omics = gsub("both", "CyTOF+scRNAseq", Omics),
                Omics = gsub("scRNA-seq", "scRNAseq", Omics),
                Omics = gsub("CYTOF", "CyTOF", Omics),
                MMR = gsub(" - request", "", MMR),
                MMR = gsub(" \\(methyl\\)", "", MMR),
                MMR = gsub("results in reffering hospital", "NA", MMR),
                MMR = gsub("HC", NA, MMR),
                MMR = gsub("NA", NA, MMR),
                MMR = gsub("Unclear from sample", "Unknown", MMR),
                MMR = gsub("no resection", "Unknown", MMR),
                Cancer_stage = gsub("(HC|NA)", NA, Cancer_stage),
                T_stage = gsub("(HC|NA)", NA, T_stage),
                N_stage = gsub("(HC|NA)", NA, N_stage),
                M_stage = gsub("(HC|NA)", NA, M_stage),
                Tumor_omics = gsub("both", "*#", Tumor_omics),
                Tumor_omics = gsub("scRNAseq", "*", Tumor_omics),
                Tumor_omics = gsub("CyTOF", "#", Tumor_omics),
                Tumor_omics = gsub("no", "", Tumor_omics),
                label = ifelse(!is.na(Tumor_omics), paste0(PatientID, Tumor_omics), PatientID)
  ) %>%
  dplyr::select(label, MAPS_CRC, MAPS_GC, PF_ATLAS, PatientID, Tumor_omics, Sex, Age, BMI, Group, Omics, MMR, Cancer_stage, T_stage, N_stage, M_stage, PM, HIPEC) %>%
  dplyr::filter(Group != "IBD_CD") %>%
  dplyr::filter(PatientID %in% ueg_samples$Donor)
rownames(patient_metadata) <- patient_metadata$PatientID  

patient_metadata <- patient_metadata[order(patient_metadata$PM),]

patient_metadata_labels <- mapply(function(x, y) {
  ifelse(!is.na(y), qq("@{x}<sup>@{y}</sup>"), qq("@{x}"))
  #qq("@{x}<sup>@{y}</sup>")
}, x = patient_metadata$PatientID, y = patient_metadata$Tumor_omics)
```

```{r figure heatmap patient metadata, fig.width = 15, fig.height = 10}
all_patient_metadata <- patient_metadata %>%
  dplyr::filter(MAPS_CRC == "Yes" | MAPS_GC == "Yes" | PF_ATLAS == "Yes")

all_patient_metadata_labels <- mapply(function(x, y) {
  ifelse(!is.na(y), qq("@{x}<sup>@{y}</sup>"), qq("@{x}"))
  #qq("@{x}<sup>@{y}</sup>")
}, x = all_patient_metadata$PatientID, y = all_patient_metadata$Tumor_omics)

all_patient_metadata_plot <- HeatmapAnnotation(patientID = anno_text(x = gt_render(all_patient_metadata_labels, 
                                                                                   align_widths = TRUE), 
                                                                     just = "left", 
                                                                     location = 0.25),
                                               Sex = all_patient_metadata$Sex,
                                               Age = anno_barplot(all_patient_metadata$Age, bar_width = 1, gp = gpar(fill = "#444444")),
                                               BMI = anno_barplot(all_patient_metadata$BMI, bar_width = 1, gp = gpar(fill = "#a69eb0")),
                                               PM = all_patient_metadata$PM,
                                               HIPEC = all_patient_metadata$HIPEC,
                                               `MMR primary tumor` = all_patient_metadata$MMR,
                                               `Pathological stage` = anno_simple(x = all_patient_metadata$Cancer_stage, 
                                                                                  pch = all_patient_metadata$Cancer_stage, 
                                                                                  col = c("I" = "#ffffff",
                                                                                          "II" = "#ffffff",
                                                                                          "III" = "#ffffff",
                                                                                          "IV" = "#ffffff"),
                                                                                  na_col = "#ffffff",
                                                                                  gp = gpar(col = "black")),
                                               annotation_name_side = "left", 
                                               gp = gpar(col = "black"),
                                               border = T,
                                               na_col = "#ffffff",
                                               col = list(Sex = c("Male" = "#3b55cd", 
                                                                  "Female" = "#cf3476"),
                                                          `MMR primary tumor` = c("MMRp" = "#0000ff",
                                                                                  "MMRd" = "#ff0000",
                                                                                  "Unknown" = "#a69eb0"),
                                                          HIPEC = c("Yes" = "#00BFC4",
                                                                    "No" = "#7CAE00"),
                                                          PM = c("No" = "#054f42",
                                                                 "Yes" = "#AB2020")))

pdf(width = 5.5, height = 6, file = file.path("ueg2022_patient_metadata.pdf"))
plot(all_patient_metadata_plot)
dev.off()
```

## CD4 Tregs

```{r cd4treg pfvpbmc degs}
degs_pbmcpmpvpmn <- readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l3/PMpvPMn_PBMC_manual_l3_pbmc_pf_tx_degs_results.Rds")
names(degs_pbmcpmpvpmn) <- names(readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l3/PMpvPMn_PBMC_manual_l3_pbmc_pf_tx_deseq2_results.Rds"))
degs_pfpmpvpmn <-
readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l3/PMpvPMn_PF_manual_l3_pbmc_pf_tx_degs_results.Rds")
names(degs_pfpmpvpmn) <- names(readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l3/PMpvPMn_PF_manual_l3_pbmc_pf_tx_deseq2_results.Rds"))

degs_pmpvpmn <- rbind(data.frame(degs_pbmcpmpvpmn$`CD4 Treg`, tissue = "PBMC"),
                      data.frame(degs_pfpmpvpmn$`CD4 Treg`, tissue = "PF"))
```

```{r cd4treg goi}
cd4treg_goi <- c("TNFRSF18", "TNFRSF4", "FOXP3", "TIGIT", "TNIP3", "TNFAIP3", "TOX2", "HAVCR2", "ZFP36", "IKZF4", "BTLA", "CD160", "CTLA4", "ENTPD1", "EOMES", "IKZF2", "LAG3", "PDCD1", "PTGER2", "TCF7", "TOX", "VSIR")
```

```{r cd4treg setup}
cd4treg_seuratObject <- pbmc_pf_tx_seuratObject[,pbmc_pf_tx_seuratObject$manual_l3 == "CD4 Treg"]

cd4treg_coldata <- cd4treg_seuratObject@meta.data %>%
  dplyr::select(SampleID, Donor, Sex, Tissue, Metastasis, Group) %>%
  unique()
rownames(cd4treg_coldata) <- cd4treg_coldata$SampleID

cd4treg_ueg_counts <- GetAssayData(cd4treg_seuratObject, slot = "counts")
cd4treg_ueg_counts_sample <- cd4treg_ueg_counts %*% model.matrix(~0+SampleID, data = cd4treg_seuratObject@meta.data)
colnames(cd4treg_ueg_counts_sample) <- gsub("SampleID", "", colnames(cd4treg_ueg_counts_sample))

cd4treg_ueg_counts_sample <- cd4treg_ueg_counts_sample[which(Matrix::rowSums(cd4treg_ueg_counts_sample) != 0),]

cd4treg_ueg_dds <- DESeqDataSetFromMatrix(countData = cd4treg_ueg_counts_sample,
                                                colData = cd4treg_coldata[colnames(cd4treg_ueg_counts_sample),],
                                                design = ~Tissue)
cd4treg_ueg_dds <- DESeq(cd4treg_ueg_dds)
cd4treg_ueg_rld <- rlog(cd4treg_ueg_dds)
```

```{r cd4treg pbmcpf pmpvpmn goi visualization, fig.height=10, fig.width = 12.5}
pdf(width = 15, height = 15, file = file.path("cd4treg_stratpbmcpf_pmpvpmn_goi.pdf"))
assay(cd4treg_ueg_rld)[cd4treg_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(cd4treg_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pmpvpmn), by = c("GeneID" = "gene", "Tissue" = "tissue")) %>%
  dplyr::mutate(label = paste0(Tissue, ": ", GeneID, "\np-value = ", ifelse(pvalue<0.01,
                               formatC(pvalue, digits = 2, format = "e"),
                               round(pvalue, digits = 3)))) %>%
  dplyr::filter(Tissue != "TX") %>%
  ggplot(aes(x = Metastasis, y = Expr, col = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~label, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank())
dev.off()
```

```{r cd4treg pbmcpf pmpvpmn goi visualization grouped, fig.height=10, fig.width = 12.5}
pdf(width = 10, height = 10, file = file.path("cd4treg_pbmcpf_pmpvpmn_goi.pdf"))
assay(cd4treg_ueg_rld)[cd4treg_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(cd4treg_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pmpvpmn), by = c("GeneID" = "gene", "Tissue" = "tissue")) %>%
  dplyr::mutate(
    # label = paste0(Tissue, "\np-value = ", ifelse(pvalue<0.01,
    #                                               formatC(pvalue, digits = 2, format = "e"),
    #                                               round(pvalue, digits = 3))),
    
                Group = paste0(Tissue, " ", Metastasis)) %>%
  dplyr::filter(Tissue != "TX") %>%
  ggplot(aes(x = Group, y = Expr, col = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~GeneID, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
dev.off()
```

```{r cd4treg pbmcpf pmpvpmn goi visualization grouped, fig.height=10, fig.width = 12.5}
pdf(width = 12.5, height = 10, file = file.path("cd4treg_pbmcpftx_pmpvpmn_goi.pdf"))
assay(cd4treg_ueg_rld)[cd4treg_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(cd4treg_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pmpvpmn), by = c("GeneID" = "gene", "Tissue" = "tissue")) %>%
  dplyr::mutate(
    # label = paste0(Tissue, "\np-value = ", ifelse(pvalue<0.01,
    #                                               formatC(pvalue, digits = 2, format = "e"),
    #                                               round(pvalue, digits = 3))),
    
                Group = paste0(Tissue, " ", Metastasis)) %>%
  ggplot(aes(x = Group, y = Expr, col = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~GeneID, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
dev.off()
```

## C1Q macrophages

```{r c1q macrophages genes of interest}
c1q_macrophages_goi <- c("JUN", "ATF3", "ZFP36", "COL1A2", "TNFAIP3", "PIK3IP1", "GATA6", "TIMD4", "VEGFA", "CSF1R", "IL10", "TGFB1", "ITGA4", "CXCR4", "IGF1", "MRC1", "APOE", "NFKBIA", "NFKBIZ")
```

```{r c1q macrophages setup}
macrophagec1q_ueg_samples_seuratObject <- pbmc_pf_tx_seuratObject[,pbmc_pf_tx_seuratObject$manual_l4 == "Macrophages C1Q+" & pbmc_pf_tx_seuratObject@meta.data$SampleID %in% ueg_samples$SampleID]

macrophagec1q_ueg_counts <- GetAssayData(macrophagec1q_ueg_samples_seuratObject, slot = "counts")
macrophagec1q_ueg_counts_sample <- macrophagec1q_ueg_counts %*% model.matrix(~0+SampleID, data = macrophagec1q_ueg_samples_seuratObject@meta.data)
colnames(macrophagec1q_ueg_counts_sample) <- gsub("SampleID", "", colnames(macrophagec1q_ueg_counts_sample))

macrophagec1q_ueg_counts_sample <- macrophagec1q_ueg_counts_sample[which(Matrix::rowSums(macrophagec1q_ueg_counts_sample) != 0),]

macrophagec1q_ueg_dds <- DESeqDataSetFromMatrix(countData = macrophagec1q_ueg_counts_sample,
                                                colData = ueg_samples[colnames(macrophagec1q_ueg_counts_sample),],
                                                design = ~Tissue)
macrophagec1q_ueg_dds <- DESeq(macrophagec1q_ueg_dds)
macrophagec1q_ueg_rld <- rlog(macrophagec1q_ueg_dds)
```

### Dimred plot

```{r myeloid preparation}
myeloid_seuratObject <- readRDS("/media/hdd1/andrewliyim/maps_crc/output/subsets/pbmc_pf_myeloid_SeuratObject.Rds")
mnp_seuratObject <- myeloid_seuratObject[,which(myeloid_seuratObject@meta.data$manual_l2 %in% c("CDCs", "Macrophages", "Monocytes", "PDCs"))]

mnp_seuratObject <- DietSeurat(mnp_seuratObject, counts = T, data = T, scale.data = F)
mnp_seuratObject <- mnp_seuratObject[Matrix::rowSums(mnp_seuratObject) != 0, ]

mnp_seuratObject <- SCTransform(mnp_seuratObject, conserve.memory = T)
mnp_seuratObject <- RunPCA(object = mnp_seuratObject, npcs = 100, seed.use = 4312897)
mnp_seuratObject <- FindNeighbors(mnp_seuratObject, reduction = "pca", dims = 1:68)
mnp_seuratObject <- FindClusters(mnp_seuratObject, resolution = 0.5, verbose = FALSE)
mnp_seuratObject <- RunUMAP(mnp_seuratObject, dims = 1:68, seed.use = 9781432)

mnp_seuratObject_umap_df <- data.frame(Embeddings(mnp_seuratObject[["umap"]]),
                                           mnp_seuratObject@meta.data) %>%
  dplyr::mutate(manual_l2_number = as.numeric(as.factor(manual_l2)),
                manual_l2_w_number = paste0(as.numeric(as.factor(manual_l2)), ". ", manual_l2),
                manual_l3_number = as.numeric(as.factor(manual_l3)),
                manual_l3_w_number = paste0(as.numeric(as.factor(manual_l3)), ". ", manual_l3),
                manual_l4_number = as.numeric(as.factor(manual_l4)),
                manual_l4_w_number = paste0(as.numeric(as.factor(manual_l4)), ". ", manual_l4),
                Group1 = factor(ifelse(Group == "HC", "HC", "CRC"), levels = c("CRC", "HC")),
                Group2 = factor(Group, levels = c("HC", "CRC-", "CRC+")))
```

```{r myeloid UMAP col_manual_l2 split_tissue}
pdf(file = "pbmc_mnp_umap.pdf", width = 15, height = 7.5)
mnp_seuratObject_umap_df %>%
  dplyr::filter(Tissue == "PBMC") %>%
  ggplot(aes(x = UMAP_1, y = UMAP_2)) +
  geom_point_rast(show.legend = T, size = 2, col = "black") +
  geom_point_rast(show.legend = T, size = 1, aes(col = manual_l2_w_number)) +
  labs(y = "",
       x = "") +
  geom_label_repel(data = mnp_seuratObject_umap_df %>%
                     dplyr::group_by(manual_l2_number, manual_l2_w_number) %>%
                     summarize(x = median(x = UMAP_1),
                               y = median(x = UMAP_2)),
                   mapping = aes(label = manual_l2_number, x = x, y = y, col = manual_l2_w_number),
                   alpha = 1, 
                   show.legend = F) +
  guides(colour = guide_legend(override.aes = list(size = 3))) +
  labs(subtitle = "PBMC mononuclear phagocytes") +
  facet_grid(.~Group2) +
  theme_minimal() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        legend.pos = "bottom",
        legend.title = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        strip.text.x = element_text(face = "bold"),
        strip.text.y = element_text(face = "bold"))
dev.off()
```

### C1Q macrophages: PM+ TXvPF 

```{r c1q macrophages txvpf degs}
pf_tx_macrophagec1q_uegpmp_samples_seuratObject <- pbmc_pf_tx_seuratObject[,pbmc_pf_tx_seuratObject$manual_l4 == "Macrophages C1Q+" &
                                                                             pbmc_pf_tx_seuratObject@meta.data$SampleID %in% ueg_samples$SampleID &
                                                                             pbmc_pf_tx_seuratObject@meta.data$Group == "CRC+" &
                                                                             pbmc_pf_tx_seuratObject@meta.data$Tissue %in% c("TX", "PF")]

pf_tx_macrophagec1q_uegpmp_samples <- unique(pf_tx_macrophagec1q_uegpmp_samples_seuratObject@meta.data[,c("SampleID", "Donor", "Tissue")])
rownames(pf_tx_macrophagec1q_uegpmp_samples) <- pf_tx_macrophagec1q_uegpmp_samples$SampleID

pf_tx_macrophagec1q_uegpmp_counts <- GetAssayData(pf_tx_macrophagec1q_uegpmp_samples_seuratObject, slot = "counts")
pf_tx_macrophagec1q_uegpmp_counts_sample <- pf_tx_macrophagec1q_uegpmp_counts %*% model.matrix(~0+SampleID, data = pf_tx_macrophagec1q_uegpmp_samples_seuratObject@meta.data)
colnames(pf_tx_macrophagec1q_uegpmp_counts_sample) <- gsub("SampleID", "", colnames(pf_tx_macrophagec1q_uegpmp_counts_sample))

pf_tx_macrophagec1q_uegpmp_counts_sample <- pf_tx_macrophagec1q_uegpmp_counts_sample[which(Matrix::rowSums(pf_tx_macrophagec1q_uegpmp_counts_sample) != 0),]

pf_tx_macrophagec1q_uegpmp_dds <- DESeqDataSetFromMatrix(countData = pf_tx_macrophagec1q_uegpmp_counts_sample,
                                                         colData = pf_tx_macrophagec1q_uegpmp_samples[colnames(pf_tx_macrophagec1q_uegpmp_counts_sample),],
                                                         design = ~Tissue)
pf_tx_macrophagec1q_uegpmp_dds <- DESeq(pf_tx_macrophagec1q_uegpmp_dds)

degs_pfvtx_macrophagec1q_uegpmp <- results(pf_tx_macrophagec1q_uegpmp_dds, name = "Tissue_TX_vs_PF")
degs_pfvtx_macrophagec1q_uegpmp <- degs_pfvtx_macrophagec1q_uegpmp[!is.na(degs_pfvtx_macrophagec1q_uegpmp$padj),]
degs_pfvtx_macrophagec1q_uegpmp <- degs_pfvtx_macrophagec1q_uegpmp[order(degs_pfvtx_macrophagec1q_uegpmp$pvalue),]
degs_pfvtx_macrophagec1q_uegpmp$gene <- rownames(degs_pfvtx_macrophagec1q_uegpmp)

pf_tx_macrophagec1q_uegpmp_rld <- rlog(pf_tx_macrophagec1q_uegpmp_dds)

pdf(width = 12.5, height = 10, file = file.path("c1q_macrophages_txvpf_goi_pmp.pdf"))
assay(pf_tx_macrophagec1q_uegpmp_rld)[c1q_macrophages_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(pf_tx_macrophagec1q_uegpmp_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pfvtx_macrophagec1q_uegpmp), by = c("GeneID" = "gene")) %>%
  dplyr::mutate(label = paste0(GeneID, "\np-value = ", formatC(pvalue, digits = 2, format = "e"))) %>%
  ggplot(aes(x = Tissue, y = Expr, col = Tissue)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~label, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank())
dev.off()
```


```{r c1q macrophages txvpf goi visualization, fig.height=10, fig.width = 12.5}
pdf(width = 12.5, height = 10, file = file.path("c1q_macrophages_txvpf_goi_pmp.pdf"))
assay(macrophagec1q_ueg_rld)[c1q_macrophages_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(macrophagec1q_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(degs_txvpf_c1qp_macrophages, by = c("GeneID" = "gene")) %>%
  dplyr::mutate(label = paste0(GeneID, "\np-value = ", formatC(pvalue, digits = 2, format = "e"))) %>%
  dplyr::filter(Tissue != "PBMC",
                Group != "CRC-") %>%
  ggplot(aes(x = Tissue, y = Expr, col = Tissue)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~label, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank())
dev.off()
```

### C1Q macrophages: PF: PM+vPM- 

```{r c1q macrophages pmpvpmn degs}
degs_pfpmpvpmn_c1qp_macrophages <- readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l4/PMpvPMn_PF_manual_l4_pbmc_pf_tx_degs_results.Rds")
names(degs_pfpmpvpmn_c1qp_macrophages) <- names( readRDS("/media/hdd1/andrewliyim/maps_crc/output/analyses/pbmc_pf_tx/de/PMpvPMn/manual_l4/PMpvPMn_PF_manual_l4_pbmc_pf_tx_deseq2_results.Rds"))
```

```{r c1q macrophages pf pmpvpmn goi visualization, fig.height=10, fig.width = 12.5}
pdf(width = 12.5, height = 10, file = file.path("c1q_macrophages_pf_pmpvpmn_goi.pdf"))
assay(macrophagec1q_ueg_rld)[c1q_macrophages_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(macrophagec1q_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pfpmpvpmn_c1qp_macrophages$`Macrophages C1Q+`), by = c("GeneID" = "gene")) %>%
  dplyr::mutate(label = paste0(GeneID, "\np-value = ", ifelse(pvalue<0.01,
                               formatC(pvalue, digits = 2, format = "e"),
                               round(pvalue, digits = 3)))) %>%
  dplyr::filter(Tissue == "PF") %>%
  ggplot(aes(x = Group, y = Expr, col = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~label, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank())
dev.off()
```

```{r c1q macrophages pftx pmpvpmn goi visualization, fig.height=12.5, fig.width = 16}
pdf(width = 16, height = 12.5, file = file.path("c1q_macrophages_pftx_pmpvpmn_goi.pdf"))
assay(macrophagec1q_ueg_rld)[c1q_macrophages_goi,] %>%
  data.frame(., GeneID = rownames(.)) %>%
  tidyr::pivot_longer(-GeneID, names_to = "SampleID", values_to = "Expr") %>%
  dplyr::left_join(data.frame(colData(macrophagec1q_ueg_rld)), by = "SampleID") %>%
  dplyr::left_join(data.frame(degs_pfpmpvpmn_c1qp_macrophages$`Macrophages C1Q+`), by = c("GeneID" = "gene")) %>%
  dplyr::mutate(label = paste0(GeneID, "\np-value = ", ifelse(pvalue<0.01,
                               formatC(pvalue, digits = 2, format = "e"),
                               round(pvalue, digits = 3))),
                Group = paste0(Group, " (", Tissue, ")")) %>%
  dplyr::filter(Tissue != "PBMC") %>%
  ggplot(aes(x = Group, y = Expr, col = Group)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter() +
  labs(y = bquote(log[2]~"(expression)")) +
  facet_wrap(~label, scales = "free_y") +
  theme_bw() +
  theme(panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        axis.title.x = element_blank())
dev.off()
```