#!/usr/bin/env Rscript

# This script will perform the differential expression pathway analyses against the M1 and M2 gene sets generated by Azizi et al. 2018 comparing CRC with HC for PF macrophages only.

require(Seurat)
require(dplyr)
require(DESeq2)
require(openxlsx)
require(fgsea)

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 4) {
  stop(paste0("Script needs 4 arguments. Current input is:", args))
}

deseq2_list_rds <- args[1]
azizi2018_xlsx <- args[2]
fgsea_list_rds <- args[3]
fgsea_list_xlsx <- args[4]

deseq2_list <- readRDS(deseq2_list_rds)

macrophages_deseq2_list <- deseq2_list[c("Macrophages VCAN+", "Macrophages C1Q+", "Macrophages VCAN+C1Q+", "Macrophages C1Q+SPP1+", "Macrophages VCAN+SPP1+")]

genesets <- list(M1 = readxl::read_excel(azizi2018_xlsx, sheet = 2)$HGNC,
                 M2 = readxl::read_excel(azizi2018_xlsx, sheet = 3)$HGNC)

fgsea_list <- lapply(macrophages_deseq2_list, function(deg_object){
  degs_df <- deg_object$degs %>%
    data.frame() %>%
    dplyr::filter(!is.na(gene))
  
  waldstats <- degs_df$stat
  names(waldstats) <- degs_df$gene
  
  fgsea_obj <- fgsea(pathways = genesets, 
                     stats = waldstats,
                     #minSize  = 15,
                     maxSize  = 500)
  
  fgsea_obj <- fgsea_obj[order(fgsea_obj$pval),]
  
  return(fgsea_obj)
})

saveRDS(fgsea_list, fgsea_list_rds)

write.xlsx(lapply(fgsea_list, function(fgsea_obj){
  data.frame(fgsea_obj[,1:7])
}), file = fgsea_list_xlsx)

sessionInfo()
